### ISSUE TITLE
add css

### ISSUE THREAD

**Issue by hanggaga** [gojuukaze/django-ktag#1]
could we add css per each of tag object ? or random css per each
just like
`const states = [
                        'success',
                        'brand',
                        'danger',
                        'success',
                        'warning',
                        'dark',
                        'primary',
                        'info'];
tagData.class = 'states.getRandomInt(0, 7);`

**Comment by gojuukaze** [comment]
The js code was not written by me. You can submit an issue in [tagify](https://github.com/yairEO/tagify)
