### ISSUE TITLE
1.0.18 breaks pattern

### ISSUE THREAD

**Issue by fritterhoff** [gojuukaze/django-ktag#3]
https://github.com/gojuukaze/django-tagify2/blob/f17d5e6f243a1be88fba767bb07dbb5af28b4eb0/tagify/templates/tagify/tagify_input.html#L8

Should be `maxTags` 

https://github.com/gojuukaze/django-tagify2/blob/f17d5e6f243a1be88fba767bb07dbb5af28b4eb0/tagify/templates/tagify/tagify_input.html#L9

Should be `pattern`

**Comment by gojuukaze** [comment]
fixed
